#
# Product-specific compile-time definitions.
#
USE_CAMERA_STUB := true

include device/telechips/tcc8902/BoardConfigVendor.mk

# The above file contains proprietary stuff and is generated by extract-files.sh which calls setup-makefiles.sh

TARGET_BOARD_PLATFORM := tcc92xx
TARGET_ARCH_VARIANT := armv5te-vfp
TARGET_CPU_ABI := armeabi
LOCAL_ARM_MODE := arm

TARGET_PREBUILT_KERNEL := device/telechips/tcc8902/kernel

TARGET_BOOTLOADER_BOARD_NAME := tcc8902
TARGET_PROVIDES_INIT_RC := true

# We have our own bootloader
TARGET_NO_BOOTLOADER := true
# Board uses no radio image
TARGET_NO_RADIOIMAGE := true
# We have our own recovery
TARGET_NO_RECOVERY := true 


BOARD_KERNEL_CMDLINE := console=ttySAC0 androidboot.hardware=tcc92xx
BOARD_KERNEL_BASE := 0x40000000
BOARD_PAGE_SIZE := 0x00001000

# We still need to verify actual max sizes versus real rom.
BOARD_BOOTIMAGE_MAX_SIZE := $(call image-size-from-data-size,0x00280000)
BOARD_RECOVERYIMAGE_MAX_SIZE := $(call image-size-from-data-size,0x00500000)
BOARD_SYSTEMIMAGE_MAX_SIZE := $(call image-size-from-data-size,0x07500000)
BOARD_USERDATAIMAGE_MAX_SIZE := $(call image-size-from-data-size,0x04ac0000)

# The size of a block that can be marked bad.
BOARD_FLASH_BLOCK_SIZE := 131072

BOARD_CUSTOM_RECOVERY_KEYMAPPING := ../../device/telechips/tcc8902/default_recovery_ui.c

# Audio is using ALSA sound but no clue how to set that up yet.
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true
#BOARD_USES_GENERIC_AUDIO := false

# Camera needs to be disabled so we use a stub for now.
#USE_CAMERA_STUB := true

# Disable Bluetooth for now
BOARD_HAVE_BLUETOOTH := false
# We have no modem inside, maybe this is needed later on:
# BOARD_HAVE_MODEM := false

# Wifi related defines (need to be fixed, as we have prebuilt kernel, w/ no source.
# There is an AR6000 on board, we have working modules and stuff under 2.1 :)
BOARD_HAVE_WIFI := true
BOARD_WPA_SUPPLICANT_DRIVER :=WEXT
WIFI_DRIVER_MODULE_PATH :=  "/system/wifi/ar6000.ko"
WIFI_DRIVER_MODULE_ARG      := ""
WIFI_DRIVER_MODULE_NAME     := "ar6000"
WIFI_FIRMWARE_LOADER        := ""

WITH_JIT := true
TARGET_HAVE_TSLIB:=true
#JS_ENGINE:=v8
ENABLE_JSC_JIT:=true
BUILD_WITH_FULL_STAGEFRIGHT:=true

## Generate descriptive build.id
DISPLAY_BUILD_NUMBER := true
