#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEVICE=tcc8902

mkdir -p ../../../device/telechips/$DEVICE/proprietary

adb wait-for-devices

# Note: akmd is needed for rotation/g-sensor, maybe needed for M701 later on
#adb pull /system/bin/akmd ../../../device/telechips/$DEVICE/proprietary/akmd
# Note: No working bluetooth found in any kernel so far. High hopes unfounded?
#adb pull /system/bin/bluetoothd ../../../device/telechips/$DEVICE/proprietary/bluetoothd

adb pull /system/lib/libaudio.so ../../../device/telechips/$DEVICE/proprietary/libaudio.so
adb pull /system/lib/libaudiopolicy.so ../../../device/telechips/$DEVICE/proprietary/libaudiopolicy.so
adb pull /system/lib/libcamera.so ../../../device/telechips/$DEVICE/proprietary/libcamera.so
adb pull /system/lib/libasound.so ../../../device/telechips/$DEVICE/proprietary/libasound.so
adb pull /system/lib/liba2dp.so ../../../device/telechips/$DEVICE/proprietary/liba2dp.so

chmod 755 ../../../device/telechips/$DEVICE/proprietary/*


(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../device/telechips/$DEVICE/device_$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/telechips/__DEVICE__/extract-files.sh

PRODUCT_COPY_FILES := \\
    device/telechips/__DEVICE__/proprietary/ar6000.ko:system/wifi/ar6000.ko \\
    device/telechips/__DEVICE__/proprietary/athwlan.bin.z77:system/wifi/athwlan.bin.z77 \\
    device/telechips/__DEVICE__/proprietary/calData_ar6102_15dBm.bin:system/wifi/calData_ar6102_15dBm.bin \\
    device/telechips/__DEVICE__/proprietary/data.patch.hw2_0.bin:system/wifi/data.patch.hw2_0.bin

PRODUCT_COPY_FILES += \\
    device/telechips/__DEVICE__/proprietary/gralloc.tcc92xx.so:system/lib/hw/gralloc.tcc92xx.so  \\
    device/telechips/__DEVICE__/proprietary/lights.tcc92xx.so:system/lib/hw/lights.tcc92xx.so \\
    device/telechips/__DEVICE__/proprietary/overlay.tcc92xx.so:system/lib/hw/overlay.tcc92xx.so \\
    device/telechips/__DEVICE__/proprietary/sensors.tcc92xx.so:system/lib/hw/sensors.tcc92xx.so \\
    device/telechips/__DEVICE__/proprietary/egl.cfg:system/lib/egl/egl.cfg \\
    device/telechips/__DEVICE__/proprietary/libEGL_mali.so:system/lib/egl/libEGL_mali.so \\
    device/telechips/__DEVICE__/proprietary/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \\
    device/telechips/__DEVICE__/proprietary/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \\
    device/telechips/__DEVICE__/proprietary/libMali.so:system/lib/libMali.so \\
    device/telechips/__DEVICE__/proprietary/mali.ko:system/lib/modules/mali.ko \\
    device/telechips/__DEVICE__/proprietary/qwerty.kcm.bin:system/usr/keychars/qwerty.kcm.bin \\
    device/telechips/__DEVICE__/proprietary/qwerty2.kcm.bin:system/usr/keychars/qwerty2.kcm.bin \\
    device/telechips/__DEVICE__/proprietary/USB-compliant_keyboard.kcm.bin:system/usr/keychars/USB-compliant_keyboard.kcm.bin \\
    device/telechips/__DEVICE__/proprietary/telechips_keypad.kl:system/usr/keylayout/telechips_keypad.kl \\
    device/telechips/__DEVICE__/proprietary/USB-compliant_keyboard.kl:system/usr/keylayout/USB-compliant_keyboard.kl \\
    device/telechips/__DEVICE__/proprietary/h2w_headset.kl:system/usr/keylayout/h2w_headset.kl \\
    device/telechips/__DEVICE__/proprietary/alsa.conf:system/usr/share/alsa/alsa.conf \\
    device/telechips/__DEVICE__/proprietary/aliases.conf:system/usr/share/alsa/cards/aliases.conf \\
    device/telechips/__DEVICE__/proprietary/default.conf:system/usr/share/alsa/pcm/default.conf \\
    device/telechips/__DEVICE__/proprietary/asound.conf:system/etc/asound.conf \\
    device/telechips/__DEVICE__/proprietary/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \\
    device/telechips/__DEVICE__/proprietary/wpa_supplicant.conf:system/etc/wpa_supplicant.conf \\
    device/telechips/__DEVICE__/proprietary/wlan_tool:/system/bin/wlan_tool \\
    device/telechips/__DEVICE__/proprietary/wmiconfig:/system/bin/wmiconfig \\
    device/telechips/__DEVICE__/proprietary/iwconfig:/system/bin/iwconfig \\
    device/telechips/__DEVICE__/proprietary/iwlist:/system/bin/iwlist \\
    device/telechips/__DEVICE__/proprietary/vold.fstab:/system/etc/vold.fstab \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.aacdec.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.apedec.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.flacdec.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.mp3enc.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.VideoDec.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.VPUDec.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.aacenc.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.audio.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.mp2dec.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.pcmdec.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.VideoEnc.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.VPUEnc.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.ac3dec.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.base.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.mp3dec.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.radec.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.vorbisdec.so:/system/lib \\
    device/telechips/__DEVICE__/proprietary/libOMX.TCC.wmadec.so:/system/lib \\
EOF

./setup-makefiles.sh
